#!/bin/bash
export LC_ALL=C

if [ -z $1 ]; then
	echo "Usage: $0 DIR1 [DIR2]"
	echo "Rename all files and directories from UPPERCASE to lowercase"
	echo
	echo "Example: $0 FEDATA GAMEDATA"
	exit
fi

echo -n "Do you want to set proper permissions for every file and directory? [Y/n]: "
read -n 1 setPerm
if [ -z $setPerm ]; then
	setPerm='1'
elif [ $setPerm == 'N' ] || [ $setPerm == 'n' ]; then
	setPerm='0'
	echo
else
	setPerm='1'
	echo
fi

for arg in $@; do
	if [ -e $arg ]; then
		if [ $setPerm == '1' ]; then
			chmod -c -R 755 $arg #Change everything to 755, because directories must be executable
			chmod -c -x $(find $arg -type f) #Remove executable flag from every file
		fi
		paths=$(find $arg -depth) || continue
		for path in $paths; do
			directory=$(dirname $path) || continue
			oldFileName=$(basename $path) || continue
			newFileName=$(echo $oldFileName | tr [:upper:] [:lower:]) || continue
			echo -n "Rename '$directory/$oldFileName'->'$directory/$newFileName' "
			if [ ! -z $directory ] && [ ! -z $oldFileName ] && [ ! -z $newFileName ]; then
				mv "$directory/$oldFileName" "$directory/$newFileName" && echo
			else
				echo "error"
			fi
		done
	else
		echo "'$arg' doesn't exist!"
	fi
done
